import Head from 'next/head';

export default function Home() {
  return (
    <>
      <div className="container">
        <Head>
          <title>Media Mall</title>
          <meta name="description" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
      </div>
      <main>
        <div className="md:flex max-w-full min-w-full">
          <div className="md:w-3/4 md:pt-24 lg:pt-24 md:px-0 lg:px-0 px-8">
            <h2
              className="lg:mt-5 md:mt-5 mt-6 md:pl-16  md:leading-normal lg:leading-normal font-bold text-4xl md:text-6xl lg:text-6xl text-gray-800">Everything <span
              className="bg-blue-300">media</span> in one <span className="bg-blue-300">place</span></h2>
          </div>
          <div className="md:w-3/4 lg:w-3/4 md:px-0 lg:px-0 lg:py-16 md:py-14 px-8 py-16">
            <img src="/images/drone.png" alt="drone landing" />
          </div>
        </div>
        <div className="md:mx-16 lg:mx-16 mx-4">
          <div className="text-center py-9">
            <h6 className="text-red-500 font-medium title">Services</h6>
            <h3 className="font-bold text-4xl text-gray-800">What We Do</h3>
          </div>
          <div className="grid md:grid-cols-3 grid-cols-1 gap-6 my-8">
            <div className="border-2 p-4 col-span-1">
              <div className="md:flex grid lg:flex justify-between items-center">
                <img src="/images/ux.png" alt="" className="md:order-1 lg:order-1 order-2 w-24" />
                <h4 className="text-4xl text-gray-200 font-bold md:order-2 lg:order-2 order-1 mb-4">01</h4>
              </div>
              <h4 className="text-2xl font-bold py-3.5 text-gray-800">Photography</h4>
              <div className="text-gray-500">
                <p className="mb-3">Mobile App, Website</p>
                <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue.
                  Cras ut.</p>
              </div>
            </div>
            <div className="border-2 p-4 col-span-1">
              <div className="md:flex grid lg:flex justify-between items-center">
                <img src="/images/remote.png" alt="" className="md:order-1 lg:order-1 order-2 w-24" />
                  <h4 className="text-4xl text-gray-200 font-bold md:order-2 lg:order-2 order-1 mb-4">02</h4>
              </div>
              <h4 className="text-2xl font-bold py-3.5 text-gray-800">Videography</h4>
              <div className="text-gray-500">
                <p className="mb-3">Mobile App, Website</p>
                <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue.
                  Cras ut.</p>
              </div>
            </div>
            <div className="border-2 p-4 col-span-1">
              <div className="md:flex grid lg:flex justify-between items-center">
                <img src="/images/graphics-design.png" alt="" className="md:order-1 lg:order-1 order-2 w-24" />
                <h4 className="text-4xl text-gray-200 font-bold md:order-2 lg:order-2 order-1 mb-4">03</h4>
              </div>
              <h4 className="text-2xl font-bold py-3.5 text-gray-800">Graphic Design</h4>
              <div className="text-gray-500">
                <p className="mb-3">Mobile App, Website</p>
                <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue.
                  Cras ut.</p>
              </div>
            </div>
            <div className="border-2 p-4 col-span-1">
              <div className="md:flex grid lg:flex justify-between items-center">
                <img src="/images/billboard.png" alt="" className="md:order-1 lg:order-1 order-2 w-24" />
                <h4 className="text-4xl text-gray-200 font-bold md:order-2 lg:order-2 order-1 mb-4">04</h4>
              </div>
              <h4 className="text-2xl font-bold py-3.5 text-gray-800">Ads/Billboards</h4>
              <div className="text-gray-500">
                <p className="mb-3">Mobile App, Website</p>
                <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue.
                  Cras ut.</p>
              </div>
            </div>
            <div className="border-2 p-4 col-span-1">
              <div className="md:flex grid lg:flex justify-between items-center">
                <img src="/images/print.png" alt="" className="md:order-1 lg:order-1 order-2 w-24" />
                <h4 className="text-4xl text-gray-200 font-bold md:order-2 lg:order-2 order-1 mb-4">05</h4>
              </div>
              <h4 className="text-2xl font-bold py-3.5 text-gray-800">Prints</h4>
              <div className="text-gray-500">
                <p className="mb-3">Mobile App, Website</p>
                <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue.
                  Cras ut.</p>
              </div>
            </div>
            <div className="border-2 p-4 col-span-1">
              <div className="md:flex grid lg:flex justify-between items-center">
                <img src="/images/format.png" alt="" className="md:order-1 lg:order-1 order-2 w-24" />
                <h4 className="text-4xl text-gray-200 font-bold md:order-2 lg:order-2 order-1 mb-4">06</h4>
              </div>
              <h4 className="text-2xl font-bold py-3.5 text-gray-800">Large Formats</h4>
              <div className="text-gray-500">
                <p className="mb-3">Mobile App, Website</p>
                <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue.
                  Cras ut.</p>
              </div>
            </div>
          </div>
        </div>
        <div className="bg-gray-100 p-4">
          <div
            className="md:w-4/5 lg:mx-auto md:mx-auto lg:w-4/5 m-auto md:grid lg:grid md:grid-cols-5 grid-cols-2 gap-8 my-8 justify-center items-center gap-4 md:my-20 lg:my-20">
            <div className="col-span-2">
              <img src="/logo/media-academy.png" alt="" className="ml-auto md:w-full lg:w-full" />
            </div>
            <div className="col-span-3 text-left py-5 md:py-9 lg:py-9 md:px-0 lg:px-0">
              <h6 className="text-red-500 font-medium title">Academic</h6>
              <h3 className="font-bold text-2xl lg:mb-20 md:mb-16">Media Training Center</h3>
              <p className="font-bold text-4xl md:text-5xl lg:text-5xl my-4 lg:mb-20 md:mb-16">A fully equipped, expert
                facilitated</p>
              <div className="md:mt-10 lg:mt-10 mt-5">
                <a className="btn px-10" href="#">Enroll</a>
                <a
                  className="border-2 font-medium px-4 py-2 tracking-wider text-sm uppercase rounded-lg border-blue-500 shadow-lg hover:text-blue-50 hover:bg-blue-500"
                  href="#">Learn More</a>
              </div>
            </div>
          </div>
        </div>
        <div className="lg:grid md:grid-cols-5 grid-cols-2 gap-8 md:p-16 lg:p-16 p-4">
          <div className="col-span-3">
          </div>
          <div className="col-span-2">
            <h6 className="text-red-500 font-medium text-center py-5 title">Recent Jobs</h6>
            <img src="/images/queen.png" alt="" className="" />
              <div className="mb-3">
                <h4 className="text-2xl font-bold py-4">Sediong Ukoka</h4>
                <p>The best thing was learning from people that cared enough to go beyond their means to guarantee you
                  learn.</p>
              </div>
              <div className="mt-6">
                <a className="btn" href="#">View More</a>
              </div>
          </div>
        </div>
        <div
          className="lg:my-20 md:my-20 my-6 lg:p-16 md:p-16 p-4 md:grid lg:grid grid-cols-3 lg:mx-auto md:mx-auto lg:w-3/4 md:w-3/4 text-indigo-50 justify-between items-center lg:gap-8 md:gap-8"
          style={{backgroundImage: " url('images/face-of-mediamall.png')", backgroundSize: "cover"}}>
          <div className="col-span-2">
            <h3 className="font-medium text-3xl mb-3">Face of MediaMall</h3>
            <p>Lorem ipsum dolor sit amet, consec tet ur adipiscing elit. Accumsan sed faucibu s faucibus augue. Cras
              ut.</p>
          </div>
          <div className="col-span-1 lg:text-right md:text-right mt-6">
            <a href="#"
               className="p-2 bg-indigo-50 text-blue-500 rounded-lg hover:bg-blue-500 font-medium hover:text-blue-50">Apply
              Now</a>
          </div>
        </div>
        <div>
          <div className="text-center pb-4 md:pb-9 lg:pb-9">
            <h6 className="text-red-500 font-medium title">Recent Jobs</h6>
            <h3 className="font-bold text-4xl">The Gallery</h3>
          </div>
          <div className="bg-gray-100 my-8 p-4 lg:p-16 md:p-16">
            <div className="grid md:grid-cols-3 grid-cols-1 gap-6">
              <div className="md:p-4 lg:p-4 col-span-1">
                <img src="/images/road.png" alt="" className="hover:opacity-70" />
              </div>
              <div className="md:p-4 lg:p-4 col-span-1">
                <img src="/images/drone.png" alt="" className="hover:opacity-75" />
              </div>
              <div className="md:p-4 lg:p-4 col-span-1">
                <img src="/images/houses.png" alt="" className="hover:opacity-75" />
              </div>
            </div>
            <div className="text-center mt-6">
              <a href="" className="btn" type="button"> View More </a>
            </div>
          </div>
        </div>
        <div className="md:p-16 lg:p-16 p-4 md:grid md:grid-cols-5 lg:grid lg:grid-cols-5 gap-8">
          <div className="col-span-2 md:order-1 lg:order-1 order-2">
            <h3 className="font-bold text-4xl mb-9">Contact Us</h3>
            <form>
              <div className="md:w-full my-2">
                <input
                  className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500"
                  id="fname" type="text" placeholder="First Name" />
              </div>
              <div className="md:w-full my-2">
                <input
                  className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500"
                  id="lname" type="text" placeholder="Last Name" />
              </div>
              <div className="md:w-full my-2">
                <input
                  className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500"
                  id="email" type="email" placeholder="Email" />
              </div>
              <div className="md:w-full my-2">
                <input
                  className="bg-gray-200 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500"
                  id="phone" type="text" placeholder="Phone Number" />
              </div>
              <div className="md:w-full my-2">
                <textarea
                  className="bg-gray-200 leading-loose row-span-5 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-blue-500"
                  defaultValue="Your message here" id="message" />
              </div>
              <div className="md:flex md:items-center">
                <div className="md:w-full">
                  <button className="btn" type="button">Sign Up</button>
                </div>
              </div>
            </form>
          </div>
          <div className="col-span-3 md:order-2 lg:order-2 order-1">
            <img src="/images/contact.png" alt="" />
          </div>
        </div>
      </main>
    </>
  )
}
